# Generated by Django 4.0.3 on 2022-07-06 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TblSecurityLog',
            fields=[
                ('id', models.AutoField(db_column='fld_ai_id', primary_key=True, serialize=False)),
                ('log_type', django_mysql.models.EnumField(blank=True, choices=[('offline', 'Offline'), ('disable tracking', 'Disable Tracking'), ('changes datetime', 'Changes Datetime')], db_column='fld_log_type', null=True)),
                ('device_info', django_mysql.models.FixedCharField(blank=True, db_column='fld_device_info', max_length=255, null=True)),
                ('ip_address', django_mysql.models.FixedCharField(blank=True, db_column='fld_ip_address', max_length=100, null=True)),
                ('is_active', models.BooleanField(db_column='fld_is_active', default=True)),
                ('is_delete', models.BooleanField(db_column='fld_is_delete', default=False)),
                ('created_datetime', models.DateField(auto_now_add=True, db_column='fld_created_datetime')),
                ('user_id', models.ForeignKey(blank=True, db_column='fld_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_security_log',
                'managed': True,
            },
        ),
    ]
