# Generated by Django 4.0.3 on 2022-06-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_tblusersites_assigned_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblusersites',
            name='sites',
        ),
        migrations.AddField(
            model_name='tblusersites',
            name='sites',
            field=models.CharField(blank=True, db_column='fld_sites', max_length=255, null=True),
        ),
    ]
