# Generated by Django 4.0.3 on 2022-06-15 13:19

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_remove_tblusersites_sites_tblusersites_sites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbluserreimbursements',
            name='status',
            field=django_mysql.models.EnumField(blank=True, choices=[('approved', 'approved'), ('pending', 'pending'), ('requested', 'requested'), ('closed', 'closed')], db_column='fld_status', default='pending', null=True),
        ),
    ]
