# Generated by Django 4.0.3 on 2022-06-15 14:26

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_tbluserreimbursements_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblattendance',
            name='fld_attendance_status',
            field=django_mysql.models.EnumField(blank=True, choices=[('check_in', 'check_in'), ('current', 'current'), ('check_out', 'check_out')], null=True),
        ),
    ]
