# Generated by Django 4.0.3 on 2022-06-15 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0006_alter_tblattendance_fld_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbluserdevices',
            name='fld_user_id',
            field=models.ForeignKey(blank=True, db_column='fld_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
