# Generated by Django 4.0.3 on 2022-06-15 15:18

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_alter_tbluserdevices_fld_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblattendance',
            name='fld_attendance_status',
            field=django_mysql.models.EnumField(blank=True, choices=[('check_in', 'Check In'), ('current', 'Current'), ('check_out', 'Check Out')], null=True),
        ),
        migrations.AlterField(
            model_name='tbluserreimbursements',
            name='status',
            field=django_mysql.models.EnumField(blank=True, choices=[('approved', 'Approved'), ('pending', 'Pending'), ('requested', 'Requested'), ('closed', 'Closed')], db_column='fld_status', default='pending', null=True),
        ),
    ]
