# Generated by Django 4.0.3 on 2022-06-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_alter_tblattendance_fld_attendance_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblattendance',
            name='auto_check_out',
            field=models.BooleanField(db_column='fld_auto_check_out', default=False),
        ),
    ]
