# Generated by Django 4.0.3 on 2022-06-22 18:50

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_tblattendance_auto_check_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblrates',
            name='fld_type',
            field=django_mysql.models.EnumField(blank=True, choices=[('two_wheeler', 'Two Wheeler'), ('four_wheeler', 'Four Wheeler'), ('others', 'Others')], db_column='fld_type', default='others', null=True),
        ),
    ]
