# Generated by Django 4.0.3 on 2022-06-21 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TblNotificationConfig',
            fields=[
                ('id', models.AutoField(db_column='fld_ai_id', primary_key=True, serialize=False)),
                ('notification_type', django_mysql.models.EnumField(blank=True, choices=[('forgets to check-in', 'Forgets To Check In'), ('forgets to check-out', 'Forgets To Check Out'), ('site reached', 'Site Reached'), ('offline', 'Offline'), ('outside of geolocation bound', 'Outside Of Geolocation Bound'), ('disable tracking', 'Disable Tracking'), ('changes datetime', 'Changes Datetime')], db_column='fld_notification_type', null=True)),
                ('notification_title', django_mysql.models.FixedCharField(blank=True, db_column='fld_notification_title', default='NA', max_length=100, null=True)),
                ('notification_body', django_mysql.models.FixedCharField(blank=True, db_column='fld_notification_body', default='NA', max_length=200, null=True)),
                ('notification_icon', models.CharField(blank=True, db_column='fld_notification_icon', default='NA', max_length=255, null=True)),
                ('is_active', models.BooleanField(db_column='fld_is_active', default=True)),
                ('is_delete', models.BooleanField(db_column='fld_is_delete', default=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, db_column='fld_created_datetime')),
            ],
            options={
                'db_table': 'tbl_notification_config',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblUserFirebase',
            fields=[
                ('id', models.AutoField(db_column='fld_ai_id', primary_key=True, serialize=False)),
                ('firebase_id', django_mysql.models.FixedCharField(blank=True, db_column='fld_firebase_id', default='NA', max_length=255, null=True)),
                ('is_send_push', models.BooleanField(db_column='fld_is_send_push', default=True)),
                ('device_info', django_mysql.models.FixedCharField(db_column='fld_device_info', default='NA', max_length=200)),
                ('is_active', models.BooleanField(db_column='fld_is_active', default=True)),
                ('is_delete', models.BooleanField(db_column='fld_is_delete', default=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, db_column='fld_created_datetime')),
                ('user_id', models.ForeignKey(blank=True, db_column='fld_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_user_firebase',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblPushNotificationLog',
            fields=[
                ('id', models.AutoField(db_column='fld_ai_id', primary_key=True, serialize=False)),
                ('firebase_response', django_mysql.models.FixedCharField(blank=True, db_column='fld_firebase_response', default='NA', max_length=250, null=True)),
                ('status_code', django_mysql.models.FixedCharField(blank=True, db_column='fld_status_code', default='NA', max_length=5, null=True)),
                ('notification_title', django_mysql.models.FixedCharField(db_column='fld_notification_title', default='NA', max_length=100)),
                ('notification_description', django_mysql.models.FixedCharField(db_column='fld_notification_description', default='NA', max_length=200)),
                ('is_success', models.BooleanField(db_column='fld_is_success', default=True)),
                ('is_active', models.BooleanField(db_column='fld_is_active', default=True)),
                ('is_delete', models.BooleanField(db_column='fld_is_delete', default=False)),
                ('datetime', models.DateTimeField(db_column='fld_datetime')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, db_column='fld_created_datetime')),
                ('notification_type_id', models.ForeignKey(blank=True, db_column='fld_notification_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.tblnotificationconfig')),
                ('user_firebase', models.ForeignKey(blank=True, db_column='fld_user_firebase', null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.tbluserfirebase')),
                ('user_id', models.ForeignKey(blank=True, db_column='fld_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_push_notification_log',
                'managed': True,
            },
        ),
    ]
