# Generated by Django 4.0.3 on 2022-06-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblpushnotificationlog',
            name='firebase_response',
            field=models.TextField(blank=True, db_column='fld_firebase_response', default='NA', null=True),
        ),
        migrations.AlterField(
            model_name='tbluserfirebase',
            name='firebase_id',
            field=models.CharField(blank=True, db_column='fld_firebase_id', default='NA', max_length=255, null=True),
        ),
    ]
