# Generated by Django 4.0.3 on 2022-06-22 11:50

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_tbluserfirebase_firebase_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblpushnotificationlog',
            name='notification_description',
            field=django_mysql.models.FixedCharField(blank=True, db_column='fld_notification_description', default='NA', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tblpushnotificationlog',
            name='notification_title',
            field=django_mysql.models.FixedCharField(blank=True, db_column='fld_notification_title', default='NA', max_length=100, null=True),
        ),
    ]
